version: '3.8'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-app-java-swing
    depends_on:
      - db
    environment:
      # Configuración de JPA para conectarse a la base de datos MySQL
      # El "hostname" de la base de datos es el nombre del servicio, 'db'
      - DATABASE_URL=jdbc:mysql://db:3306/Culturarte?zeroDateTimeBehavior=CONVERT_TO_NULL
      - DATABASE_USER=tecnologo
      - DATABASE_PASSWORD=tecnologo
      # Configuración para el reenvío de la GUI
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  db:
    image: mysql:8.0.17
    container_name: mi-base-de-datos
    environment:
      MYSQL_ROOT_PASSWORD: tecnologo
      MYSQL_DATABASE: Culturarte
      MYSQL_PASSWORD: tecnologo
      MYSQL_USER: tecnologo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: