/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import logica.IController;
import logica.Fabrica;
import logica.DTO.DTORegistrosAccesoWeb;

/**
 *
 * @author klaas
 */
public class AccessReg extends javax.swing.JInternalFrame {

    private final IController controller = Fabrica.getInstance().getController();
    private Timer t;
    int pass = 0;   //Esto es para que la primera vez averigue si hay elementos o si no, si hay, se recargará automáticamente.
            
    public AccessReg() 
    {
        initComponents();
        updater();
    }
    
    @Override
    public void dispose() 
    {   //Se sobrecarga dispose para que tambíen pare el timer cuando se cierra ventana de cualquer manera
        if (t != null)
        {   
            t.stop();
        }
        super.dispose();
    }
    
    private void updater() //Con esto consigo que el sistema actualice solo y no sobrecargue tanto, cada 2 seg
    {
        descargarInfo();
        
        if(t == null & pass == 1)    //Solo se usa si hay elementos
        {
            t = new Timer(2000, e -> descargarInfo());
            t.start();
        }
    }
    
    public void descargarInfo()
    {     
        SwingWorker<Void, Void> worker; 
        
        worker = new SwingWorker<>() 
        {
            private final DefaultListModel<String> modelo = new DefaultListModel<>();
               
            //Proceso segundo plano obteniendo datos de db
            @Override
            protected Void doInBackground() 
            {
                List<DTORegistrosAccesoWeb> accesos = controller.obtenerRegistrosAccesoWeb();
                
                if (accesos != null && !accesos.isEmpty()) 
                {
                    for (DTORegistrosAccesoWeb reg : accesos) 
                    {
                        if (reg != null && reg.getAcceso() != null)
                        {
                            modelo.addElement(reg.getAcceso());
                        }
                    }
                    
                    pass = 1;   //Se puede repetir.
                }
                else
                {
                    pass = 0;
                    
                    if (t != null)
                    {
                        t.stop();   
                    }
                }
                
                return null;
            }
           
            @Override //Luego dependiendo de como finalice arriba se hace esto...
            protected void done() 
            {
                if (pass == 0) //Saco para que no quede una pantalla vacía
                {
                    JOptionPane.showMessageDialog(AccessReg.this,"No hay registros actualmente","Culturarte Workstation",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                else    //Si hay algo, setea los datos en tabla
                {
                    ListaRegistro.setModel(modelo);
                }
            }
        }; 
        
        worker.execute(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaRegistro = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registros de Acceso Web");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        jLabel1.setText("Registros de este mes:");

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        ListaRegistro.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cargando...", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaRegistro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonSalir))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        
        if (t != null)  //Detengo el timer
        {
            t.stop();
        }
        
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JList<String> ListaRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
