/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import logica.IController;
import logica.Fabrica;
import logica.DTO.DTORegistrosAccesoWeb;

/**
 *
 * @author klaas
 */
public class AccessReg extends javax.swing.JInternalFrame {

    private final IController controller = Fabrica.getInstance().getController();
    private Timer t;
    int pass = 0;   //Esto es para que la primera vez averigue si hay elementos o si no, si hay, se recargará automáticamente.
            
    public AccessReg() 
    {
        initComponents();
        descargarInfo();
        
    }
    
    @Override
    public void dispose() 
    {   //Se sobrecarga dispose para que tambíen pare el timer cuando se cierra ventana de cualquer manera
        if (t != null)
        {   
            t.stop();
        }
        super.dispose();
    }
    
    private void updater() //Con esto consigo que el sistema actualice solo y no sobrecargue tanto, cada 2 seg
    {
        if(t == null && pass == 1)    //Solo se usa si hay elementos
        {
            t = new Timer(2000, e -> descargarInfo());
            t.start();
        }
    }
    
    public void descargarInfo()
    {     
        SwingWorker<Void, Void> worker; 
        
        worker = new SwingWorker<>() 
        {
            private final DefaultTableModel modelo = new DefaultTableModel(new String[]{"#", "IP", "URL", "Navegador", "SO"}, 0) 
            {
                @Override
                public boolean isCellEditable(int row, int column) 
                {
                    return false; 
                }
            };
               
            //Proceso segundo plano obteniendo datos de db
            @Override
            protected Void doInBackground() 
            {
                List<DTORegistrosAccesoWeb> accesos = controller.obtenerRegistrosAccesoWeb();
                
                if (accesos != null && !accesos.isEmpty()) 
                {
                    modelo.setRowCount(0);
                    
                    for (DTORegistrosAccesoWeb reg : accesos) 
                    {
                        if (reg != null && reg.getAcceso() != null)
                        {
                            modelo.addRow(new Object[]{reg.getId(),reg.getIp(),reg.getUrl(),reg.getNavegadorWeb(),reg.getSO() });
                        }
                    }
                    
                    pass = 1;   //Se puede repetir.
                }
                else
                {
                    pass = 0;
                    
                    if (t != null)
                    {
                        t.stop();   
                    }
                }
                
                return null;
            }
           
            @Override //Luego dependiendo de como finalice arriba se hace esto...
            protected void done() 
            {
                if (pass == 0) //Saco para que no quede una pantalla vacía
                {
                    JOptionPane.showMessageDialog(AccessReg.this,"No hay registros actualmente","Culturarte Workstation",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                else    //Si hay algo, setea los datos en tabla
                {
                    tablaDatos.setModel(modelo);
                    
                    tablaDatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                    
                    tablaDatos.getColumnModel().getColumn(0).setPreferredWidth(60); 
                    tablaDatos.getColumnModel().getColumn(1).setPreferredWidth(150);
                    tablaDatos.getColumnModel().getColumn(2).setPreferredWidth(400); 
                    tablaDatos.getColumnModel().getColumn(3).setPreferredWidth(60); 
                    tablaDatos.getColumnModel().getColumn(4).setPreferredWidth(60); 
                    
                    tablaDatos.revalidate();
                    tablaDatos.repaint();
                    
                    if(pass == 1)
                    {
                       updater();
                    }
                }
            }
        }; 
        
        worker.execute(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registros de Acceso Web");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        jLabel1.setText("Registros de los últimos 30 días:");

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonSalir))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        
        if (t != null)  //Detengo el timer
        {
            t.stop();
        }
        
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
