package ui;

/**
 *
 * @author klaas
 */
public class AltaDeCategoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alta_Categoria
     */
    public AltaDeCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollLista = new javax.swing.JScrollPane();
        listaCategorias = new javax.swing.JTable();
        subTitulo = new javax.swing.JLabel();
        labelAgregarCategoria = new javax.swing.JLabel();
        campoNombreNuevaCategoria = new javax.swing.JTextField();
        botonAgregarCategoria = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Nueva Categoría...");
        setToolTipText("Añadir");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        scrollLista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                scrollListaFocusLost(evt);
            }
        });

        listaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Categoria", "Subcategorías"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollLista.setViewportView(listaCategorias);
        if (listaCategorias.getColumnModel().getColumnCount() > 0) {
            listaCategorias.getColumnModel().getColumn(0).setMinWidth(110);
            listaCategorias.getColumnModel().getColumn(0).setPreferredWidth(120);
            listaCategorias.getColumnModel().getColumn(0).setMaxWidth(130);
        }

        subTitulo.setText("Categorías disponibles actualmente");

        labelAgregarCategoria.setText("Añadir categoría nueva");

        campoNombreNuevaCategoria.setText("Ingrese nombre categoría...");
        campoNombreNuevaCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreNuevaCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreNuevaCategoriaFocusLost(evt);
            }
        });
        campoNombreNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreNuevaCategoriaActionPerformed(evt);
            }
        });

        botonAgregarCategoria.setText("Agregar...");
        botonAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAgregarCategoria)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAgregarCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNombreNuevaCategoria)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(subTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAgregarCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarCategoria)
                    .addComponent(campoNombreNuevaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scrollListaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scrollListaFocusLost
        //Se recupera el texto si no se escribe nada y quitan el foco ahi...

    }//GEN-LAST:event_scrollListaFocusLost

    private void campoNombreNuevaCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreNuevaCategoriaFocusGained
        //Con esto, si se hace clic se quita la label...
        if (campoNombreNuevaCategoria.getText().equals("Ingrese nombre categoría...")) 
        {
            campoNombreNuevaCategoria.setText("");    
        }
    }//GEN-LAST:event_campoNombreNuevaCategoriaFocusGained

    private void campoNombreNuevaCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreNuevaCategoriaFocusLost
        //Se recupera el texto si no se escribe nada y quitan el foco ahi...
        if (campoNombreNuevaCategoria.getText().isEmpty()) 
        {
             campoNombreNuevaCategoria.setText("Ingrese nombre categoría...");
        }
    }//GEN-LAST:event_campoNombreNuevaCategoriaFocusLost

    private void campoNombreNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreNuevaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreNuevaCategoriaActionPerformed

    private void botonAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarCategoriaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        //TODO
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

        //TODO
    }//GEN-LAST:event_formFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCategoria;
    private javax.swing.JTextField campoNombreNuevaCategoria;
    private javax.swing.JLabel labelAgregarCategoria;
    private javax.swing.JTable listaCategorias;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JLabel subTitulo;
    // End of variables declaration//GEN-END:variables
}
