/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logica.Fabrica;
import logica.IController;
import logica._enum.TipoRetorno;
import logica.DTO.DTFecha;
import logica.DTO.DTOProponente;
import logica.DTO.DTOCategoria;

public class AltaPropuesta extends javax.swing.JInternalFrame {
    private IController controller = Fabrica.getInstance();
    private String rutaImagen = null; 

    /**
     * Creates new form AltaPropuesta
     */
    public AltaPropuesta(/*Map<String, DTOProponente> mapProp,Map<String, DTOCategoria> mapCat*/) {
        initComponents();
  /*      ListaUsuarios.removeAllItems();
        ListaCategoria.removeAllItems();
        Retorno1.removeAllItems();
        
        for (DTOCategoria c :mapCat.values())
        {
            ListaCategoria.addItem(c);
        }
        
        for (DTOProponente p :mapProp.values())
        {
            ListaUsuarios.addItem(p);
        }
        
        //Falta la lista de retornos
      */  
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloAgregarPropuesta = new javax.swing.JLabel();
        ListaUsuarios = new javax.swing.JComboBox<>();
        IngresoUsuario = new javax.swing.JLabel();
        IngresoCategoria = new javax.swing.JLabel();
        ListaCategoria = new javax.swing.JComboBox<>();
        Titulo = new javax.swing.JLabel();
        TituloField = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        Precio_Entrada = new javax.swing.JLabel();
        Monto_A_Recaudar = new javax.swing.JLabel();
        Descripcion_Field = new javax.swing.JTextField();
        Tipo_Field = new javax.swing.JTextField();
        Lugar_Field = new javax.swing.JTextField();
        Precio_Field = new javax.swing.JTextField();
        Monto_Field = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Imagen_Boton = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Retorno1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Propuesta");

        TituloAgregarPropuesta.setText("Ingrese los siguientes datos");

        ListaUsuarios.setToolTipText("");
        ListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaUsuariosActionPerformed(evt);
            }
        });

        IngresoUsuario.setText("Proponente");

        IngresoCategoria.setText("Categoria");

        ListaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCategoriaActionPerformed(evt);
            }
        });

        Titulo.setText("Titulo");

        TituloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloFieldActionPerformed(evt);
            }
        });

        Descripcion.setText("Descripcion");

        Tipo.setText("Tipo");

        Lugar.setText("Lugar");

        Precio_Entrada.setText("Precio Entrada");

        Monto_A_Recaudar.setText("Monto a recaudar");

        Descripcion_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descripcion_FieldActionPerformed(evt);
            }
        });

        Tipo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_FieldActionPerformed(evt);
            }
        });

        Lugar_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lugar_FieldActionPerformed(evt);
            }
        });

        Precio_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_FieldActionPerformed(evt);
            }
        });

        Monto_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Monto_FieldActionPerformed(evt);
            }
        });

        Agregar.setText("Crear");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");

        Imagen_Boton.setText("Subir");
        Imagen_Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imagen_BotonActionPerformed(evt);
            }
        });

        Imagen.setText("Imagen");

        jLabel7.setText("Fecha ");

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        jLabel8.setText("Anio");

        jLabel9.setText("Mes");

        jLabel10.setText("Dia");

        jLabel6.setText("Retorno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(TituloAgregarPropuesta))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(IngresoUsuario)
                                    .addGap(12, 12, 12)
                                    .addComponent(ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(IngresoCategoria)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ListaCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Retorno1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Lugar)
                                        .addComponent(Tipo)
                                        .addComponent(Descripcion)
                                        .addComponent(Titulo))
                                    .addGap(226, 226, 226)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addComponent(Precio_Entrada)
                                            .addGap(26, 26, 26))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Monto_A_Recaudar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(9, 9, 9)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lugar_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Monto_Field)
                                            .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Tipo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Descripcion_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(Imagen)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Agregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cancelar))
                                .addComponent(Imagen_Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TituloAgregarPropuesta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IngresoUsuario))
                    .addComponent(ListaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresoCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Retorno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(TituloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo)
                    .addComponent(Tipo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugar_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precio_Entrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Monto_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Monto_A_Recaudar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imagen_Boton)
                    .addComponent(Imagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Agregar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void envioDato(){  
        String titulo = TituloField.getText();
        String descripcion = Descripcion_Field.getText();
        String tipo = Tipo_Field.getText();
        String lugar = Lugar_Field.getText();
        String precio = Precio_Field.getText();
        String montoTotal = Monto_Field.getText();
        int dia = Integer.parseInt(d.getText());
        int mes = Integer.parseInt(m.getText());
        int anio = Integer.parseInt(a.getText());
        DTFecha fechaEvento = new DTFecha(dia, mes, anio);
        DTOProponente proponente = (DTOProponente) ListaUsuarios.getSelectedItem();
        DTOCategoria categoria = (DTOCategoria) ListaCategoria.getSelectedItem();
        TipoRetorno retorno = (TipoRetorno) Retorno1.getSelectedItem();
       
        if (titulo.isEmpty() && descripcion.isEmpty() && tipo.isEmpty() && lugar.isEmpty() && precio.isEmpty() && montoTotal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
            return; 
        } 
        else{
            controller.altaPropuesta(titulo, descripcion, tipo, rutaImagen, lugar, fechaEvento, precio, montoTotal, retorno, categoria, proponente);
            JOptionPane.showMessageDialog(this, "Propuesta creada correctamente");
        }
    }
           
    private void TituloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloFieldActionPerformed
        
    }//GEN-LAST:event_TituloFieldActionPerformed

    private void Descripcion_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descripcion_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Descripcion_FieldActionPerformed

    private void Tipo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tipo_FieldActionPerformed

    private void Lugar_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lugar_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lugar_FieldActionPerformed

    private void Precio_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_FieldActionPerformed

    private void Monto_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monto_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Monto_FieldActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        envioDato();
    }//GEN-LAST:event_AgregarActionPerformed

    private void Imagen_BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imagen_BotonActionPerformed
        JFileChooser fileProp = new JFileChooser();
        fileProp .setDialogTitle("Seleccionar imagen");
        fileProp .setFileSelectionMode(JFileChooser.FILES_ONLY);
     
        fileProp.setAcceptAllFileFilterUsed(false);
        fileProp .addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Imagenes", "jpg","png"));

        int resultado = fileProp.showOpenDialog(this); 

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileProp.getSelectedFile();
            rutaImagen= archivo.getAbsolutePath(); 
           // System.out.println("Imagen seleccionada: " + rutaImagen);
        }
    }//GEN-LAST:event_Imagen_BotonActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed

    }//GEN-LAST:event_dActionPerformed

    private void ListaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCategoriaActionPerformed
/*
        DTOCategoria seleccionado = (DTOCategoria) ListaCategoria.getSelectedItem();

        if (seleccionado != null )
        {
            //si selecciona algo mal (en proceso)
        }
        */
    }//GEN-LAST:event_ListaCategoriaActionPerformed

    private void ListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaUsuariosActionPerformed

        /*
        DTOProponente seleccionado = (DTOProponente) ListaUsuarios.getSelectedItem();

        if (seleccionado != null )
        {
            //si selecciona algo mal (en proceso)
        }

        */
    }//GEN-LAST:event_ListaUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextField Descripcion_Field;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton Imagen_Boton;
    private javax.swing.JLabel IngresoCategoria;
    private javax.swing.JLabel IngresoUsuario;
    private javax.swing.JComboBox<DTOCategoria> ListaCategoria;
    private javax.swing.JComboBox<DTOProponente> ListaUsuarios;
    private javax.swing.JLabel Lugar;
    private javax.swing.JTextField Lugar_Field;
    private javax.swing.JLabel Monto_A_Recaudar;
    private javax.swing.JTextField Monto_Field;
    private javax.swing.JLabel Precio_Entrada;
    private javax.swing.JTextField Precio_Field;
    private javax.swing.JComboBox<String> Retorno1;
    private javax.swing.JLabel Tipo;
    private javax.swing.JTextField Tipo_Field;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloAgregarPropuesta;
    private javax.swing.JTextField TituloField;
    private javax.swing.JTextField a;
    private javax.swing.JTextField d;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField m;
    // End of variables declaration//GEN-END:variables
}
