package ui;
import logica.DTO.DTOPropuesta;
import logica.DTO.DTORegistro_Estado;
import javax.swing.DefaultListModel;

/**
 *
 * @author klaas
 */
public class MostrarDatosPropuesta extends javax.swing.JInternalFrame {

    DTOPropuesta datos = new DTOPropuesta();
 
    public MostrarDatosPropuesta() {
        initComponents();
        
    }
    
    public void inicializarLista() 
    {
        DefaultListModel<String> listaFinal = new DefaultListModel<>();
        
        DTORegistro_Estado ultimoEstado = datos.getUltimoEstado();
        
        listaFinal.addElement(datos.getTitulo());
        listaFinal.addElement(datos.getDescripcion());
        listaFinal.addElement(datos.getTipo());
        listaFinal.addElement(datos.getLugar());
        listaFinal.addElement(datos.getFecha().getFechaString());
        listaFinal.addElement(datos.getPrecio());
        listaFinal.addElement(datos.getMontoTotal());
        listaFinal.addElement(datos.getFechaPublicacion().getFechaString());
        listaFinal.addElement(datos.getRetorno().toString());
        listaFinal.addElement(datos.getCategoria().getNombreCategoria());
        listaFinal.addElement(datos.getProponente().getNombre());
        listaFinal.addElement(datos.getTitulo());
        listaFinal.addElement(ultimoEstado.getEstadoString());      //Estado actual
        listaFinal.addElement(ultimoEstado.getFechaRegString());    //Muestra la fecha del ultimo estado

        listaDatos.setModel(listaFinal);
        
        listaDatos.setFixedCellHeight(50); //(Distancia vertical entre elementos) Hasta que no se pueda probar, no puedo saber cuanto ajustar el parámetro
    }

    public void SetDatosPropuesta(DTOPropuesta almacenDatos)
    {
        datos = almacenDatos;   //datos seleccionados que vienen de la UI anterior se almacenan
        inicializarLista();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpanel = new javax.swing.JScrollPane();
        listaDatos = new javax.swing.JList<>();
        subTituloEtiqueta = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labDescripcion = new javax.swing.JLabel();
        labelProp = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelMonto = new javax.swing.JLabel();
        labelFechaPubl = new javax.swing.JLabel();
        labelCat = new javax.swing.JLabel();
        labelNombreProponente = new javax.swing.JLabel();
        panelDeImagen = new javax.swing.JPanel();
        lel = new javax.swing.JLabel();
        borrarLuego = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Propuedades de Propuesta");

        listaDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listaDatos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        listaDatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollpanel.setViewportView(listaDatos);

        subTituloEtiqueta.setText("Informacón general de la propuesta");

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        labelTitulo.setText("Título");

        labDescripcion.setText("Descripción");

        labelProp.setText("Tipo de Propuesta");

        labelPrecio.setText("Precio");

        labelFecha.setText("Fecha");

        labelMonto.setText("Monto a recaudar");

        labelFechaPubl.setText("Fecha de Publicación");

        labelCat.setText("Categoría");

        labelNombreProponente.setText("Proponente");

        panelDeImagen.setBackground(new java.awt.Color(153, 255, 153));

        lel.setFont(new java.awt.Font("Gayathri Thin", 1, 14)); // NOI18N
        lel.setForeground(new java.awt.Color(0, 0, 0));
        lel.setText("404_imagen_de_propuesta_not_found_lol");

        javax.swing.GroupLayout panelDeImagenLayout = new javax.swing.GroupLayout(panelDeImagen);
        panelDeImagen.setLayout(panelDeImagenLayout);
        panelDeImagenLayout.setHorizontalGroup(
            panelDeImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lel)
                .addGap(16, 16, 16))
        );
        panelDeImagenLayout.setVerticalGroup(
            panelDeImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeImagenLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addComponent(lel))
        );

        borrarLuego.setText("aun hay que ajustar altura de la Jlist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrarLuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(subTituloEtiqueta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProp)
                            .addComponent(labDescripcion)
                            .addComponent(labelTitulo)
                            .addComponent(labelPrecio)
                            .addComponent(labelFecha)
                            .addComponent(labelMonto)
                            .addComponent(labelFechaPubl)
                            .addComponent(labelCat)
                            .addComponent(labelNombreProponente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelDeImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subTituloEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(4, 4, 4)
                        .addComponent(labDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelProp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFechaPubl)
                        .addGap(3, 3, 3)
                        .addComponent(labelCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNombreProponente))
                    .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir)
                    .addComponent(borrarLuego))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose(); //Finaliza caso de uso
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrarLuego;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel labDescripcion;
    private javax.swing.JLabel labelCat;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFechaPubl;
    private javax.swing.JLabel labelMonto;
    private javax.swing.JLabel labelNombreProponente;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProp;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel lel;
    private javax.swing.JList<String> listaDatos;
    private javax.swing.JPanel panelDeImagen;
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JLabel subTituloEtiqueta;
    // End of variables declaration//GEN-END:variables
}
